[package]
name = "aery"
version = "0.1.0"
edition = "2021"
authors = ["iiYese iiyese@outlook.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
